### ISSUE TITLE
3.2.0 warning: "asmdef will not be compiled, because it has no scripts associated with it"

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#692]
**Describe the bug**
After upgrading to 3.2.0, I'm getting the following warning on every recompile: `Assembly for Assembly Definition File 'Packages/com.playeveryware.eos/Runtime/com.playeveryware.eos.asmdef' will not be compiled, because it has no scripts associated with it.`

**Desktop (please complete the following information):**
 - OS: Win 11
 - Editor
 - 2022.3.30
 - 3.2.0

**Comment by 3ternal** [comment]
`EOS_DISABLE` seems to have stopped working as well, because I'm getting this error on console platforms: `Library\PackageCache\com.playeveryware.eos@3.2.0\Runtime\Core\EOSManager.cs(79,32): error CS0246: The type or namespace name 'Epic' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by arthur740212** [comment]
`EOS_DISABLE` seems to be broken on all platforms, we are prioritizing this issue.
Thank you for the feedback.

**Comment by paulhazen** [comment]
> `EOS_DISABLE` seems to have stopped working as well, because I'm getting this error on console platforms: `Library\PackageCache\com.playeveryware.eos@3.2.0\Runtime\Core\EOSManager.cs(79,32): error CS0246: The type or namespace name 'Epic' could not be found (are you missing a using directive or an assembly reference?)`. Reverted to 3.1.1 for now.

Hi @3ternal - I've opened PR #695 to resolve this issue - the fix should be in tomorrow at the latest.

**Comment by paulhazen** [comment]
> **Describe the bug** After upgrading to 3.2.0, I'm getting the following warning on every recompile: `Assembly for Assembly Definition File 'Packages/com.playeveryware.eos/Runtime/com.playeveryware.eos.asmdef' will not be compiled, because it has no scripts associated with it.`
> 
> **Desktop (please complete the following information):**
> 
> * OS: Win 11
> * Editor
> * 2022.3.30
> * 3.2.0

I will look into this and have a solution for you by the end of the day tomorrow. I _believe_ I know what the issue is. Fortunately, while it is a warning (and may consequently break CI / CD flows) the warning is not in this case indicative of a larger unreported problem or issue. I think what we need to do is remove that `asmdef`, but I don't want to rush to do that before we have made sure that doesn't cause other headaches somewhere.

**Comment by paulhazen** [comment]
@3ternal As you may have seen from the PRs going from draft to open to draft we are still working on this issue - but it brought up a sort of philosophical question regarding best practices and how we should organize the code, and that has us considering several options. 

We to be careful when making changes to the `.asmdef` files, since it might break compatibility for some of our users. We are taking a little bit more time to triple check that the changes we want to make to resolve this issue without causing regressions for anyone else.

In the meantime - irksome as it is - you can ignore the warning (and hopefully configure your CI / CD flow to account for it).

We will have a solution in the near future.

**Comment by 3ternal** [comment]
@paulhazen Hey, thanks for the update. That's all right - I've actually gone back to 3.0.3 for now, because I was running into platform-specific on various newer versions. I can update later, once things are sorted out on your end.

**Comment by paulhazen** [comment]
Hi @3ternal. I just checked whether this warning still happens in our latest (`3.3.0` as of the time of this writing) release, and it appears to have been resolved. If you'd like to upgrade to that version, there are quite a few improvements (summarized in the release notes attached to the 6 releases between the version you are utilizing and the latest one).

If, while making that upgrade you are still experiencing issues of any kind, we would love to hear about them. For the sake of clarity of purpose please do so by opening a new issue, as I am going to mark this one as resolved and close the issue.
